forer11/GroupStudyingApp

.idea/.name
app/google-services.json
app/src/main/java/com/example/groupstudyingapp/Answer.java
app/src/main/java/com/example/groupstudyingapp/Course.java
app/src/main/java/com/example/groupstudyingapp/FireStoreHandler.java
app/src/main/java/com/example/groupstudyingapp/MainActivity.java
app/src/main/java/com/example/groupstudyingapp/Question.java

Added classes for course, question and answer.

30.5 started working on DB

---

app/src/main/res/drawable/course_layout.xml

changes the courses buttons to be more round with spaces between them

make course buttons round with margin

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java

now when we press show solution it shows the first answer if there is, and if not it prints a message "no answers yet".
need to add:
1. rating for answers
2. show all answers and not just first one

show first answer or print msg if there are no answers

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/groupstudyingapp/MainActivity.java
app/src/main/java/com/example/groupstudyingapp/SendEmailActivity.java
app/src/main/res/layout/activity_main.xml
app/src/main/res/layout/activity_send_email.xml
app/src/main/res/values/strings.xml

added: new request from app manager by mail - to add a new course.

request to add a new course

---

app/src/main/java/com/example/groupstudyingapp/BaseMenuActivity.java
app/src/main/java/com/example/groupstudyingapp/OpeningScreenActivity.java
app/src/main/res/drawable/blurred_button_shape.xml
app/src/main/res/drawable/dialog_bg.xml
app/src/main/res/layout/sign_out_dialog.xml
app/src/main/res/values/styles.xml

Made profile image be dynamic with the google profile image, left the
same functionality for the signout

Added AlertDialog

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java
app/src/main/res/layout/activity_question.xml

Now, after pressing 'Show solution', a new button 'Next answer' appears, and when pressing it, the next solution is shows.
Also, the rating number, changes accordingly, and pressing it, will add a rating to the relevant answer,
solves part of #87 and part of #97

Now it is possible to see all answers and not only the first one.

---

app/src/androidTest/java/com/example/groupstudyingapp/ExampleInstrumentedTest.java

add some more tests:
* sign out test
* add answer test
* like answer test

Add more tests

---

app/src/main/java/com/example/groupstudyingapp/MovableFloatingActionButton.java
app/src/main/res/layout/activity_course_page.xml

made the button for adding question to be movable

Added flotiong button functionality

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java

add the option to unlike an answer

add the option to unlike an answer

---

app/src/main/java/com/example/groupstudyingapp/Answer.java
app/src/main/java/com/example/groupstudyingapp/DynamicImageView.java
app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java
app/src/main/res/layout/activity_question.xml

fix bug solution images get smaller

---

app/src/main/java/com/example/groupstudyingapp/MainActivity.java
app/src/main/res/layout/courses_sort_options_dialog.xml

added an option to filter the courses!

courses filter

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java
app/src/main/res/layout/activity_question.xml

as a user it took me a while to understand where the ratings were. this is more intuitive in my opinion

Kirsh change ratings ui

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java

- fix english in question-rate text-view
- add pop-up explaining where to find solution (once per launch)

update question page

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java

fix bug - update like button when going to next solution

---

app/build.gradle
app/src/androidTest/java/com/example/groupstudyingapp/AddQWithCameraTest.java
app/src/androidTest/java/com/example/groupstudyingapp/ImageViewMatcher.java
app/src/androidTest/java/com/example/groupstudyingapp/SignInAndOutTest.java

I saw your existing tests had question adding in a todo comment. Now, you can test it in AddQWithCameraTest. Please notice my issue #190, adding this requested functionality will improve testing capabilities.
Also, some time ago exiting the app it coused it to crush. I created a basic sign-in/out test for this issue, although, currently the app exists with no problems.

Added two tests and a helper class to assert image view content.

---

app/src/main/java/com/example/groupstudyingapp/CoursePageActivity.java
app/src/main/java/com/example/groupstudyingapp/FireStoreHandler.java

fix bug when open new question the app crashes

---

app/src/main/java/com/example/groupstudyingapp/FireStoreHandler.java
app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java

fix bug - new answer doesnt show

---

app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java
app/src/main/res/layout/activity_question.xml

removed the redundant space in the question activity

redundant-space-fix

---

app/src/main/res/layout/activity_question.xml

keep the visibility of the question's title when scrolling down to check the answers

title visibility

---

app/src/androidTest/java/com/example/groupstudyingapp/SendRequestActivityTest.java

In this PR I added a test for sending request

add-SendRequstActivityTest

---

app/src/androidTest/java/com/example/groupstudyingapp/AddQuestionActivityTest.java

added a test for adding a question

added a test for adding a question

---

app/src/main/java/com/example/groupstudyingapp/CoursePageActivity.java
app/src/main/java/com/example/groupstudyingapp/CoursePageAdapter.java
app/src/main/java/com/example/groupstudyingapp/Question.java
app/src/main/java/com/example/groupstudyingapp/QuestionActivity.java
app/src/main/res/drawable/ic_check_icon.xml
app/src/main/res/layout/activity_question.xml
app/src/main/res/layout/question_view.xml

#218 
now you have this button in the question activity:
and when pressing it, a check mark shows up at the question menu:

add "mark as done" option for question

---

app/src/main/java/com/example/groupstudyingapp/AddQuestionActivity.java

Fix ISSUE #226 Too long title

---

app/src/main/java/com/example/groupstudyingapp/LoginActivity.java

Fixed for google sign in and anonymous sign in
Signed-off-by: forer11 <lior.forer@cs.huji.ac.il>

Fixed multiple login press bug
